name: Build

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@v2
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Re-install requirements
        run: |
          sudo apt update
          git clone https://github.com/akhilnarang/scripts.git scripts
          cd scripts
          bash setup/android_build_env.sh
         
      - name: Initialise ROM repo
        run: |
          python repo init --depth=1 --no-repo-verify -u git://github.com/AOSiP/platform_manifest.git -b pie -g default,-mips,-darwin,-notdefault
 
      - name: Clone device repo
        run: |
          git clone https://github.com/indi121/local_manifests.git --depth 1 -b aosip-9 .repo/local_manifests
      - name: Start sync
        run: |
          python repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync 
          git config --global user.email "indira1aryal@gmail.com"
          git config --global user.name "indi121"
      - name: build rum
        run: |
          source build/envsetup.sh
          lunch aosip_whyred-userdebug
          export LC_ALL=C
          time mka kronic
