name: Build

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     # - uses: actions/checkout@v2
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Re-install requirements
        run: |
          sudo apt update
          sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          curl -O https://storage.googleapis.com/git-repo-downloads/repo
         
      - name: Initialise ROM repo
        run: |
          python repo init --depth=1 --no-repo-verify -u git://github.com/LineageOS/android.git -b lineage-17.1 -g default,-mips,-darwin,-notdefault
 
      - name: Clone device repo
        run: |
          git clone https://github.com/indi121/local_manifests.git --depth 1 -b los .repo/local_manifests
      - name: Start sync
        run: |
          python repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync 
          git config --global user.email "indira1aryal@gmail.com"
          git config --global user.name "indi121"
      - name: build rum
        run: |
          source build/envsetup.sh
          lunch lineage_vince-user
          export LC_ALL=C
          mka bacon
